log_level: DEBUG
search_concurrency: 10
search_rate: 100
token_ttl: 1m
words_address: localhost:8081
update_address: localhost:8082
search_address: localhost:8083
api_server:
  address: localhost:8080
  timeout: 5s
